### ISSUE TITLE
Dependency Problem when building for tag/release-5.10.2 with target Ubuntu 16.04 

### ISSUE THREAD

**Issue by t-hofmann** [OpenNebula/packages#126]
When installing from the resulting debian packages two dependencies could not be resolved by the underlying Ubuntu 16.04, those are:
- libcurl4
- libssl1.1

Up to now I could not pinpoint, where the dependencies are introduced.
But suitable substitutes might be among:
- libssl1.0.0
- libcurl4-nss-dev
- libcurl4-openssl-dev

Kind regards,
Thomas

**Comment by t-hofmann** [comment]
the build works if building without "export BUILD_COMPONENTS='rubygems'",
so the problem lies somewhere there.

If installing from packages built with export BUILD_COMPONENTS=""
The install runs but the services fail to start the services due to missing ruby-components.
A $> sudo /usr/share/one/install_gems also fails, since the "augeas" built/install fails.

**Comment by vholer** [comment]
Looks to me you must be building by wrong script, i.e. for Ubuntu 16.04 you must use `ubuntu1604.sh` no matter what build host are you using (e.g., we build all Debian-like platforms on Ubuntu 18.04). Dependency on libcurl4 is not introduced in ubuntu1604 packages. Also, packaging of Ruby gems is refactored in upcoming 5.12 and (library) dependencies are now automatically placed by the packager.

Yes, without rubygems package you must go through the `instlal_gems`. Failing `augeas` gem build was fixed in `one-5.10` branch.

Closing for now, please reopen if you still experience problems.
