### ISSUE TITLE
node_modules files in sunstone package

### ISSUE THREAD

**Issue by Madko** [OpenNebula/packages#81]
Hi,

Following the instructions from https://github.com/OpenNebula/packages I'm able to build packages for CentOS7. But there is a big difference from the official ones. The official RPM contain over 5K files in node_modules/ in the sunstone subpackage. Nothing in mine.

The instructions say:
rm -rf node_modules/

Are those instructions up to date ? Are they used to build official packages ?

Best regards,
Edouard

**Comment by vholer** [comment]
This inconsistency was introduced during the switch to Sunstone build script https://github.com/OpenNebula/one/blob/master/src/sunstone/public/build.sh. You are right, we are now packaging `node_modules/` since OpenNebula 5.6 although we shouldn't.

I'm not absolutely sure if the `node_modules/` in the source archive can't be of any use for any future Sunstone rebuilds with same dependencies, so I did a change https://github.com/OpenNebula/packages/commit/61c4472d1298c32e4c8762ae640916c06a504d7f
 in the packaging where we now drop the `node_modules/` (if there are any).

So, it doesn't matter if you drop it during the archive creation, it'll be dropped on package build at the end.

Thanks for notifying us.
